perform_authentication: true
login: nghia
password: 5acea2e6f2a0812810bbe1620b296ed2
blog_name: TALES
author: Nghia Duong
motto: Success. Failure. Things in between.
email: tnghia.duong@gmail.com
github: adlq

